# This is a basic workflow to help you get started with Actions

# Workflow 이름
name: CI

# 어떤 event 조건으로 workflow를 trigger 할 지에 대해 기술
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ] # Event: main branch에 push 하는 경우
  pull_request:
    branches: [ "main" ] # Event: main branch에 대해 pull request (merge request) 하는 경우

  # Allows you to run this workflow manually from the Actions tab
  # Manual하게 workflow를 실행 가능하게 함
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.12]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Settings
      - name: Set up Python $(( matirx.python-version ))
        uses: actions/setup-python@v5
        with:
          python-version: $(( matirx.python-version ))
          

      # Runs
      - name: Run main.py
        run: python3 ./main.py
